name: simpeg-torch-test
channels:
  - conda-forge
dependencies:
# dependencies
  - numpy>=1.22
  - scipy>=1.8
  - pymatsolver>=0.3
  - pytorch
  - matplotlib-base
  - libdlf
  - typing_extensions
  - simpeg


# solver
# uncomment the next line if you are on an intel platform
#  - pydiso # if on intel pc
# uncomment this line if you want to install mumps solvers
#  - python-mumps

# optional dependencies
  # - pandas

# documentation building
  # - sphinx
  # - sphinx-gallery>=0.1.13
  # - sphinxcontrib-apidoc
  # - sphinx-reredirects
  # - pydata-sphinx-theme
  # - empymod>=2.0.0
  # - nbsphinx
  # - numpydoc
  # - pillow
  # - sympy
  # - memory_profiler
  # - python-kaleido
  # - h5py

# testing
  - pytest
  - pytest-cov

# style checking
  - pre-commit
  - black==24.3.0
  - flake8==7.0.0
  - flake8-pyproject==1.2.3
  - flake8-bugbear==23.12.2
  - flake8-builtins==2.2.0
  - flake8-mutable==1.2.0
  - flake8-rst-docstrings==0.3.0
  - flake8-docstrings==1.7.0
  - zizmor # lint GitHub Actions workflows

# recommended
  - jupyter
  # - pyvista
